

data:
  users_path: "https://storage.yandexcloud.net/ds-ods/files/files/c1992ccf/users_meta.parquet"
  items_path: "https://storage.yandexcloud.net/ds-ods/files/files/13b479ed/items_meta.parquet"
  train_path: "https://storage.yandexcloud.net/ds-ods/files/data/docs/competitions/VKRecsysChallenge2024/dataset/train_interactions.parquet"
  test_path: "https://storage.yandexcloud.net/ds-ods/files/files/0235d298/test_pairs.csv"
  # weights: Tuple[float, float] = (0.5, 10.0, 20.0),
  weights: [0.35, 7.15, 850.0]
  val_size: 0.1
  batch_size: 16384
  num_workers: 2
  pin_memory: True
model:
  user_size: 183404
  item_size: 337727
  source_size: 19613
  user_emb_size: 128
  item_emb_size: 128
  source_emb_size: 32
  gender_emb_size: 8
  duration_emb_size: 8
  age_emb_size: 8
  dropout: 0.3
trainer:
  min_epochs: 1
  max_epochs: 8
  accelerator: gpu
  precision: 16
  devices: 1
  gradient_clip_algorithm: "norm"
  gradient_clip_val: 1.0
  log_every_n_steps: 1
  enable_model_summary: false
  check_val_every_n_epoch: 1
  deterministic: False
  